baseURL = "http://example.org/"
languageCode = "en-us"
title = "LDR Metadata Guidelines"
theme = "book"

[markup]
    defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookRepo = 'https://github.com/LafayetteCollegeLibraries/metadata-guidelines'
  BookDateFormat = 'Jan 2, 2006'
  BookMenuBundle = '/menu'
